[features]
seeds = false
[programs.localnet]
crowdfunding = "Np3nbC7YJhD9Cur4sU8uTt3Hov9KhKEKNEs7KUPc2Eu"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
